version: "4.3"

services:
  #MongoDB
  mongo_db:
    container_name: database_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  users_service:
    build: ./backend/users_service
    ports:
      - 8000:8000
    # env_file: ./backend/users_service/.env
    environment:
      PORT: 8000
      DB_URI: mongodb://mongo_db:27017/
      JWT_SECRET : Hamza911.code
      FRONTEND_URL : http://localhost:5173
    depends_on:
      - mongo_db
  links_service:
    build: ./backend/links_serivce 
    ports:
      - 8001:8001
    # env_file: ./backend/links_service/.env
    environment:
      PORT: 8001
      DB_URI: mongodb://mongo_db:27017/links
      JWT_SECRET : Hamza911.code
      FRONTEND_URL : http://localhost:5173
    depends_on:
      - mongo_db
      - users_service
  client_service:
    build: ./frontend
    ports:
      - 5173:5173
    environment:
      PORT: 5173
      VITE_USER_SERVICE :  http://localhost:8000
      VITE_LINK_SERVICE : http://localhost:8001 
      VITE_APP_URL : http://localhost:5173 
    depends_on:
      - mongo_db
      - users_service
      - links_service

volumes:
  mongo_db: {}